Added ability to retrieve packages by type and retrieve package metadata
spatie/packagist-api pull request #5
Opened 2018-05-03 17:25 UTC by dicarlosystems

Adds ability to retrieve list of packages by type.  Also adds a method to retrieve a specific package's metadata.

2018-05-05 21:32 UTC, freekmurze requested changes

2018-05-05 21:32 UTC, freekmurze commented on src/Packagist.php
> +        return $this->makeRequest('/packages/list.json', ['type' => $type]);
use `compact($type)` here

2018-05-05 21:33 UTC, freekmurze commented
Could you also resolve any merge conflicted and update the readme?

2018-05-08 09:59 UTC, dicarlosystems commented on src/Packagist.php
> +        return $this->makeRequest('/packages/list.json', ['type' => $type]);
Will do!

2018-05-08 10:35 UTC, dicarlosystems commented
Resolved all the conflicts, updated the README, and fixed that one typo.

2018-05-09 16:56 UTC, freekmurze approved these changes

2018-05-09 16:56 UTC, merged

2018-05-09 16:56 UTC, freekmurze commented
Thanks!